[project]
name = "rotki-aod"
version = "1.0.0"
authors = [
    {name = "rotki", email = "info@rotki.com"},
]

requires-python = ">=3.10"
dependencies = [
    "notebook==7.0.6",
    "seaborn==0.13.0",
    "polars==0.19.19",
    "pyarrow==14.0.1"
]