UPDATE asset_collections SET name='Wormhole Token', symbol='W' WHERE id=262;
INSERT INTO asset_collections(id, name, symbol) VALUES (262, "Wormhole Token", "W");
UPDATE asset_collections SET name='TokenFi', symbol='TOKEN' WHERE id=263;
INSERT INTO asset_collections(id, name, symbol) VALUES (263, "TokenFi", "TOKEN");
UPDATE asset_collections SET name='HTX', symbol='HTX' WHERE id=264;
INSERT INTO asset_collections(id, name, symbol) VALUES (264, "HTX", "HTX");
UPDATE asset_collections SET name='Patex Token', symbol='PATEX' WHERE id=265;
INSERT INTO asset_collections(id, name, symbol) VALUES (265, "Patex Token", "PATEX");
UPDATE asset_collections SET name='GAM3S.GG', symbol='G3' WHERE id=266;
INSERT INTO asset_collections(id, name, symbol) VALUES (266, "GAM3S.GG", "G3");
UPDATE asset_collections SET name='Masa Token', symbol='MASA' WHERE id=267;
INSERT INTO asset_collections(id, name, symbol) VALUES (267, "Masa Token", "MASA");
UPDATE asset_collections SET name='GameTournamentTrophy', symbol='GTT' WHERE id=268;
INSERT INTO asset_collections(id, name, symbol) VALUES (268, "GameTournamentTrophy", "GTT");
UPDATE asset_collections SET name='Port3 Network', symbol='PORT3' WHERE id=269;
INSERT INTO asset_collections(id, name, symbol) VALUES (269, "Port3 Network", "PORT3");
UPDATE asset_collections SET name='AltLayer Token', symbol='ALT' WHERE id=270;
INSERT INTO asset_collections(id, name, symbol) VALUES (270, "AltLayer Token", "ALT");
UPDATE asset_collections SET name='DeFi', symbol='DEFI' WHERE id=271;
INSERT INTO asset_collections(id, name, symbol) VALUES (271, "DeFi", "DEFI");
UPDATE asset_collections SET name='bitsCrunch Token', symbol='BCUT' WHERE id=272;
INSERT INTO asset_collections(id, name, symbol) VALUES (272, "bitsCrunch Token", "BCUT");
UPDATE asset_collections SET name='QORPO Token', symbol='QORPO' WHERE id=273;
INSERT INTO asset_collections(id, name, symbol) VALUES (273, "QORPO Token", "QORPO");
UPDATE asset_collections SET name='Truflation', symbol='TRUF' WHERE id=274;
INSERT INTO asset_collections(id, name, symbol) VALUES (274, "Truflation", "TRUF");
UPDATE asset_collections SET name='Aether Games', symbol='AEG' WHERE id=275;
INSERT INTO asset_collections(id, name, symbol) VALUES (275, "Aether Games", "AEG");
UPDATE asset_collections SET name='Amulet', symbol='AMU' WHERE id=276;
INSERT INTO asset_collections(id, name, symbol) VALUES (276, "Amulet", "AMU");
UPDATE asset_collections SET name='Brawl Token', symbol='BRAWL' WHERE id=277;
INSERT INTO asset_collections(id, name, symbol) VALUES (277, "Brawl Token", "BRAWL");
UPDATE asset_collections SET name='LightLink', symbol='LL' WHERE id=278;
INSERT INTO asset_collections(id, name, symbol) VALUES (278, "LightLink", "LL");
UPDATE asset_collections SET name='Wrapped eETH', symbol='weETH' WHERE id=279;
INSERT INTO asset_collections(id, name, symbol) VALUES (279, "Wrapped eETH", "weETH");
UPDATE asset_collections SET name='MAGA', symbol='TRUMP' WHERE id=280;
INSERT INTO asset_collections(id, name, symbol) VALUES (280, "MAGA", "TRUMP");
UPDATE asset_collections SET name='DizzyHavoc', symbol='DZHV' WHERE id=281;
INSERT INTO asset_collections(id, name, symbol) VALUES (281, "DizzyHavoc", "DZHV");
UPDATE asset_collections SET name='Ice', symbol='ICE' WHERE id=282;
INSERT INTO asset_collections(id, name, symbol) VALUES (282, "Ice", "ICE");
UPDATE asset_collections SET name='Independence Token', symbol='RFKJ' WHERE id=283;
INSERT INTO asset_collections(id, name, symbol) VALUES (283, "Independence Token", "RFKJ");
UPDATE asset_collections SET name='Aave stable debt bearing DAI v2', symbol='stableDebtDAI' WHERE id=284;
INSERT INTO asset_collections(id, name, symbol) VALUES (284, "Aave stable debt bearing DAI v2", "stableDebtDAI");
UPDATE asset_collections SET name='Aave variable debt bearing DAI v2', symbol='variableDebtDAI' WHERE id=285;
INSERT INTO asset_collections(id, name, symbol) VALUES (285, "Aave variable debt bearing DAI v2", "variableDebtDAI");
UPDATE asset_collections SET name='Aave stable debt bearing USDC v2', symbol='stableDebtUSDC' WHERE id=286;
INSERT INTO asset_collections(id, name, symbol) VALUES (286, "Aave stable debt bearing USDC v2", "stableDebtUSDC");
UPDATE asset_collections SET name='Aave variable debt bearing USDC v2', symbol='variableDebtUSDC' WHERE id=287;
INSERT INTO asset_collections(id, name, symbol) VALUES (287, "Aave variable debt bearing USDC v2", "variableDebtUSDC");
UPDATE asset_collections SET name='Aave stable debt bearing USDT v2', symbol='stableDebtUSDT' WHERE id=288;
INSERT INTO asset_collections(id, name, symbol) VALUES (288, "Aave stable debt bearing USDT v2", "stableDebtUSDT");
UPDATE asset_collections SET name='Aave variable debt bearing USDT v2', symbol='variableDebtUSDT' WHERE id=289;
INSERT INTO asset_collections(id, name, symbol) VALUES (289, "Aave variable debt bearing USDT v2", "variableDebtUSDT");
UPDATE asset_collections SET name='Aave stable debt bearing WBTC v2', symbol='stableDebtWBTC' WHERE id=290;
INSERT INTO asset_collections(id, name, symbol) VALUES (290, "Aave stable debt bearing WBTC v2", "stableDebtWBTC");
UPDATE asset_collections SET name='Aave variable debt bearing WBTC v2', symbol='variableDebtWBTC' WHERE id=291;
INSERT INTO asset_collections(id, name, symbol) VALUES (291, "Aave variable debt bearing WBTC v2", "variableDebtWBTC");
UPDATE asset_collections SET name='Aave interest bearing WETH v2', symbol='aWETH' WHERE id=292;
INSERT INTO asset_collections(id, name, symbol) VALUES (292, "Aave interest bearing WETH v2", "aWETH");
UPDATE asset_collections SET name='Aave stable debt bearing WETH v2', symbol='stableDebtWETH' WHERE id=293;
INSERT INTO asset_collections(id, name, symbol) VALUES (293, "Aave stable debt bearing WETH v2", "stableDebtWETH");
UPDATE asset_collections SET name='Aave variable debt bearing WETH v2', symbol='variableDebtWETH' WHERE id=294;
INSERT INTO asset_collections(id, name, symbol) VALUES (294, "Aave variable debt bearing WETH v2", "variableDebtWETH");
UPDATE asset_collections SET name='Aave interest bearing AAVE v2', symbol='aAAVE' WHERE id=295;
INSERT INTO asset_collections(id, name, symbol) VALUES (295, "Aave interest bearing AAVE v2", "aAAVE");
UPDATE asset_collections SET name='Aave stable debt bearing AAVE v2', symbol='stableDebtAAVE' WHERE id=296;
INSERT INTO asset_collections(id, name, symbol) VALUES (296, "Aave stable debt bearing AAVE v2", "stableDebtAAVE");
UPDATE asset_collections SET name='Aave variable debt bearing AAVE v2', symbol='variableDebtAAVE' WHERE id=297;
INSERT INTO asset_collections(id, name, symbol) VALUES (297, "Aave variable debt bearing AAVE v2", "variableDebtAAVE");
UPDATE asset_collections SET name='Safe Token', symbol='SAFE' WHERE id=298;
INSERT INTO asset_collections(id, name, symbol) VALUES (298, "Safe Token", "SAFE");
UPDATE asset_collections SET name='izumi Token', symbol='iZi' WHERE id=299;
INSERT INTO asset_collections(id, name, symbol) VALUES (299, "izumi Token", "iZi");
UPDATE asset_collections SET name='Kyber Network Crystal v2', symbol='KNC' WHERE id=300;
INSERT INTO asset_collections(id, name, symbol) VALUES (300, "Kyber Network Crystal v2", "KNC");
UPDATE asset_collections SET name='PancakeSwap Token', symbol='CAKE' WHERE id=301;
INSERT INTO asset_collections(id, name, symbol) VALUES (301, "PancakeSwap Token", "CAKE");
