name: verify

on: [push, pull_request]

jobs:
  verify-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install -r requirements.txt
    - name: Store python cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Verify changes
      run: |
        python -m pytest tests
